version: "3.5"
services:
  web3signer:
    image: "web3signer.web3signer.dnp.dappnode.eth:0.1.0"
    build:
      context: web3signer
      args:
        UPSTREAM_VERSION: 21.10.5
    ports:
      - "9003:9000"
    volumes:
      # IMPORTANT! Volume cannot be explicity the path defined at --key-store-path, otherwise there will be permission issues
      - "web3signer_data:/opt/web3signer"
    restart: unless-stopped
  postgres:
    build:
      context: postgres
      args:
        UPSTREAM_VERSION: 21.10.5
    image: "postgres.web3signer.dnp.dappnode.eth:0.1.0"
    env_file:
      - ./postgres/.env.postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: web3signer
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "postgres_migrations:/docker-entrypoint-initdb.d"
    restart: unless-stopped
volumes:
  web3signer_data: {}
  postgres_data: {}
  postgres_migrations: {}
